// Code generated by protoc-gen-go. DO NOT EDIT.
// source: review.proto

package review

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Rating struct {
	Score                int32    `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	ReviewsCount         int32    `protobuf:"varint,2,opt,name=reviews_count,json=reviewsCount,proto3" json:"reviews_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_review_25c668f4c1ec3b8d, []int{0}
}
func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (dst *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(dst, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Rating) GetReviewsCount() int32 {
	if m != nil {
		return m.ReviewsCount
	}
	return 0
}

type GetBusinessRatingRequest struct {
	BusinessUid          string   `protobuf:"bytes,1,opt,name=business_uid,json=businessUid,proto3" json:"business_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBusinessRatingRequest) Reset()         { *m = GetBusinessRatingRequest{} }
func (m *GetBusinessRatingRequest) String() string { return proto.CompactTextString(m) }
func (*GetBusinessRatingRequest) ProtoMessage()    {}
func (*GetBusinessRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_review_25c668f4c1ec3b8d, []int{1}
}
func (m *GetBusinessRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBusinessRatingRequest.Unmarshal(m, b)
}
func (m *GetBusinessRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBusinessRatingRequest.Marshal(b, m, deterministic)
}
func (dst *GetBusinessRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBusinessRatingRequest.Merge(dst, src)
}
func (m *GetBusinessRatingRequest) XXX_Size() int {
	return xxx_messageInfo_GetBusinessRatingRequest.Size(m)
}
func (m *GetBusinessRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBusinessRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBusinessRatingRequest proto.InternalMessageInfo

func (m *GetBusinessRatingRequest) GetBusinessUid() string {
	if m != nil {
		return m.BusinessUid
	}
	return ""
}

func init() {
	proto.RegisterType((*Rating)(nil), "Rating")
	proto.RegisterType((*GetBusinessRatingRequest)(nil), "GetBusinessRatingRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReviewServiceClient is the client API for ReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReviewServiceClient interface {
	GetBusinessRating(ctx context.Context, in *GetBusinessRatingRequest, opts ...grpc.CallOption) (*Rating, error)
}

type reviewServiceClient struct {
	cc *grpc.ClientConn
}

func NewReviewServiceClient(cc *grpc.ClientConn) ReviewServiceClient {
	return &reviewServiceClient{cc}
}

func (c *reviewServiceClient) GetBusinessRating(ctx context.Context, in *GetBusinessRatingRequest, opts ...grpc.CallOption) (*Rating, error) {
	out := new(Rating)
	err := c.cc.Invoke(ctx, "/ReviewService/GetBusinessRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewServiceServer is the server API for ReviewService service.
type ReviewServiceServer interface {
	GetBusinessRating(context.Context, *GetBusinessRatingRequest) (*Rating, error)
}

func RegisterReviewServiceServer(s *grpc.Server, srv ReviewServiceServer) {
	s.RegisterService(&_ReviewService_serviceDesc, srv)
}

func _ReviewService_GetBusinessRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).GetBusinessRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReviewService/GetBusinessRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).GetBusinessRating(ctx, req.(*GetBusinessRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReviewService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ReviewService",
	HandlerType: (*ReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBusinessRating",
			Handler:    _ReviewService_GetBusinessRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review.proto",
}

func init() { proto.RegisterFile("review.proto", fileDescriptor_review_25c668f4c1ec3b8d) }

var fileDescriptor_review_25c668f4c1ec3b8d = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x2d, 0xcb,
	0x4c, 0x2d, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe6, 0x62, 0x0b, 0x4a, 0x2c, 0xc9,
	0xcc, 0x4b, 0x17, 0x12, 0xe1, 0x62, 0x2d, 0x4e, 0xce, 0x2f, 0x4a, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0d, 0x82, 0x70, 0x84, 0x94, 0xb9, 0x78, 0x21, 0xea, 0x8b, 0xe3, 0x93, 0xf3, 0x4b, 0xf3,
	0x4a, 0x24, 0x98, 0xc0, 0xb2, 0x50, 0x43, 0x8a, 0x9d, 0x41, 0x62, 0x4a, 0xb6, 0x5c, 0x12, 0xee,
	0xa9, 0x25, 0x4e, 0xa5, 0xc5, 0x99, 0x79, 0xa9, 0xc5, 0xc5, 0x10, 0xf3, 0x82, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x84, 0x14, 0xb9, 0x78, 0x92, 0xa0, 0x12, 0xf1, 0xa5, 0x99, 0x29, 0x60, 0xd3,
	0x39, 0x83, 0xb8, 0x61, 0x62, 0xa1, 0x99, 0x29, 0x46, 0x5e, 0x5c, 0xbc, 0x41, 0x60, 0xe3, 0x82,
	0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x2c, 0xb9, 0x04, 0x31, 0xcc, 0x13, 0x92, 0xd4, 0xc3,
	0x65, 0x87, 0x14, 0xbb, 0x1e, 0x84, 0xaf, 0xc4, 0x90, 0xc4, 0x06, 0xf6, 0x96, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x04, 0x29, 0x81, 0x41, 0xe6, 0x00, 0x00, 0x00,
}
