# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.grpc import business_pb2 as src_dot_grpc_dot_business__pb2
from src.grpc import fingerprint_pb2 as src_dot_grpc_dot_fingerprint__pb2


class BusinessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateBusinessScore = channel.unary_unary(
                '/BusinessService/UpdateBusinessScore',
                request_serializer=src_dot_grpc_dot_business__pb2.ScoreUpdateRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_fingerprint__pb2.Empty.FromString,
                )


class BusinessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateBusinessScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BusinessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateBusinessScore': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBusinessScore,
                    request_deserializer=src_dot_grpc_dot_business__pb2.ScoreUpdateRequest.FromString,
                    response_serializer=src_dot_grpc_dot_fingerprint__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BusinessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BusinessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateBusinessScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BusinessService/UpdateBusinessScore',
            src_dot_grpc_dot_business__pb2.ScoreUpdateRequest.SerializeToString,
            src_dot_grpc_dot_fingerprint__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
