# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/business.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.grpc import fingerprint_pb2 as src_dot_grpc_dot_fingerprint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17src/grpc/business.proto\x1a\x1asrc/grpc/fingerprint.proto\"9\n\x12ScoreUpdateRequest\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x14\n\x0c\x62usiness_uid\x18\x02 \x01(\t2G\n\x0f\x42usinessService\x12\x34\n\x13UpdateBusinessScore\x12\x13.ScoreUpdateRequest\x1a\x06.Empty\"\x00\x62\x06proto3')



_SCOREUPDATEREQUEST = DESCRIPTOR.message_types_by_name['ScoreUpdateRequest']
ScoreUpdateRequest = _reflection.GeneratedProtocolMessageType('ScoreUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCOREUPDATEREQUEST,
  '__module__' : 'src.grpc.business_pb2'
  # @@protoc_insertion_point(class_scope:ScoreUpdateRequest)
  })
_sym_db.RegisterMessage(ScoreUpdateRequest)

_BUSINESSSERVICE = DESCRIPTOR.services_by_name['BusinessService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCOREUPDATEREQUEST._serialized_start=55
  _SCOREUPDATEREQUEST._serialized_end=112
  _BUSINESSSERVICE._serialized_start=114
  _BUSINESSSERVICE._serialized_end=185
# @@protoc_insertion_point(module_scope)
