# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/notifications.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.grpc import fingerprint_pb2 as src_dot_grpc_dot_fingerprint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csrc/grpc/notifications.proto\x1a\x1asrc/grpc/fingerprint.proto\"S\n\x19ReviewNotificationRequest\x12\x10\n\x08user_uid\x18\x01 \x01(\t\x12\x14\n\x0c\x62usiness_uid\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t2\xa7\x01\n\x13NotificationService\x12H\n SendUserNoticationReviewRejected\x12\x1a.ReviewNotificationRequest\x1a\x06.Empty\"\x00\x12\x46\n\x1eSendNotificationReviewAccepted\x12\x1a.ReviewNotificationRequest\x1a\x06.Empty\"\x00\x62\x06proto3')



_REVIEWNOTIFICATIONREQUEST = DESCRIPTOR.message_types_by_name['ReviewNotificationRequest']
ReviewNotificationRequest = _reflection.GeneratedProtocolMessageType('ReviewNotificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVIEWNOTIFICATIONREQUEST,
  '__module__' : 'src.grpc.notifications_pb2'
  # @@protoc_insertion_point(class_scope:ReviewNotificationRequest)
  })
_sym_db.RegisterMessage(ReviewNotificationRequest)

_NOTIFICATIONSERVICE = DESCRIPTOR.services_by_name['NotificationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REVIEWNOTIFICATIONREQUEST._serialized_start=60
  _REVIEWNOTIFICATIONREQUEST._serialized_end=143
  _NOTIFICATIONSERVICE._serialized_start=146
  _NOTIFICATIONSERVICE._serialized_end=313
# @@protoc_insertion_point(module_scope)
