# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13src/grpc/user.proto\x12\x04user\"k\n\x04User\x12\x10\n\x08\x66\x63mToken\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nwhatsappNo\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x13\n\x0bunsuspendAt\x18\x05 \x01(\x05\x12\x0b\n\x03uid\x18\x06 \x01(\t\"\x1f\n\x10UserByUidRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2C\n\x0bUserService\x12\x34\n\x0cGetUserByUid\x12\x16.user.UserByUidRequest\x1a\n.user.User\"\x00\x62\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_USERBYUIDREQUEST = DESCRIPTOR.message_types_by_name['UserByUidRequest']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'src.grpc.user_pb2'
  # @@protoc_insertion_point(class_scope:user.User)
  })
_sym_db.RegisterMessage(User)

UserByUidRequest = _reflection.GeneratedProtocolMessageType('UserByUidRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERBYUIDREQUEST,
  '__module__' : 'src.grpc.user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserByUidRequest)
  })
_sym_db.RegisterMessage(UserByUidRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'src.grpc.user_pb2'
  # @@protoc_insertion_point(class_scope:user.Empty)
  })
_sym_db.RegisterMessage(Empty)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=29
  _USER._serialized_end=136
  _USERBYUIDREQUEST._serialized_start=138
  _USERBYUIDREQUEST._serialized_end=169
  _EMPTY._serialized_start=171
  _EMPTY._serialized_end=178
  _USERSERVICE._serialized_start=180
  _USERSERVICE._serialized_end=247
# @@protoc_insertion_point(module_scope)
