# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/server/review.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.grpc import fingerprint_pb2 as src_dot_grpc_dot_fingerprint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csrc/grpc/server/review.proto\x1a\x1asrc/grpc/fingerprint.proto\"B\n\x1a\x46ingerprintCallbackRequest\x12\x12\n\nreview_uid\x18\x01 \x01(\t\x12\x10\n\x08phone_id\x18\x02 \x01(\t\".\n\x06Rating\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x15\n\rreviews_count\x18\x02 \x01(\x05\"0\n\x18GetBusinessRatingRequest\x12\x14\n\x0c\x62usiness_uid\x18\x01 \x01(\t2\x88\x01\n\rReviewService\x12<\n\x13\x46ingerprintCallback\x12\x1b.FingerprintCallbackRequest\x1a\x06.Empty\"\x00\x12\x39\n\x11GetBusinessRating\x12\x19.GetBusinessRatingRequest\x1a\x07.Rating\"\x00\x62\x06proto3')



_FINGERPRINTCALLBACKREQUEST = DESCRIPTOR.message_types_by_name['FingerprintCallbackRequest']
_RATING = DESCRIPTOR.message_types_by_name['Rating']
_GETBUSINESSRATINGREQUEST = DESCRIPTOR.message_types_by_name['GetBusinessRatingRequest']
FingerprintCallbackRequest = _reflection.GeneratedProtocolMessageType('FingerprintCallbackRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINGERPRINTCALLBACKREQUEST,
  '__module__' : 'src.grpc.server.review_pb2'
  # @@protoc_insertion_point(class_scope:FingerprintCallbackRequest)
  })
_sym_db.RegisterMessage(FingerprintCallbackRequest)

Rating = _reflection.GeneratedProtocolMessageType('Rating', (_message.Message,), {
  'DESCRIPTOR' : _RATING,
  '__module__' : 'src.grpc.server.review_pb2'
  # @@protoc_insertion_point(class_scope:Rating)
  })
_sym_db.RegisterMessage(Rating)

GetBusinessRatingRequest = _reflection.GeneratedProtocolMessageType('GetBusinessRatingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBUSINESSRATINGREQUEST,
  '__module__' : 'src.grpc.server.review_pb2'
  # @@protoc_insertion_point(class_scope:GetBusinessRatingRequest)
  })
_sym_db.RegisterMessage(GetBusinessRatingRequest)

_REVIEWSERVICE = DESCRIPTOR.services_by_name['ReviewService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FINGERPRINTCALLBACKREQUEST._serialized_start=60
  _FINGERPRINTCALLBACKREQUEST._serialized_end=126
  _RATING._serialized_start=128
  _RATING._serialized_end=174
  _GETBUSINESSRATINGREQUEST._serialized_start=176
  _GETBUSINESSRATINGREQUEST._serialized_end=224
  _REVIEWSERVICE._serialized_start=227
  _REVIEWSERVICE._serialized_end=363
# @@protoc_insertion_point(module_scope)
